# Generated by Django 3.2 on 2021-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=4)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
